controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor:
      type: imu_sensor_broadcaster/ImuSensorBroadcaster

imu_sensor:
  ros__parameters:

    interface_names.orientation.x: imu_sensor/orientation.x
    interface_names.orientation.y: imu_sensor/orientation.y
    interface_names.orientation.z: imu_sensor/orientation.z
  
    interface_names.angular_velocity.x: imu_sensor/angular_velocity.x
    interface_names.angular_velocity.y: imu_sensor/angular_velocity.y
    interface_names.angular_velocity.z: imu_sensor/angular_velocity.z
  
    interface_names.linear_acceleration.x: imu_sensor/linear_acceleration.x
    interface_names.linear_acceleration.y: imu_sensor/linear_acceleration.y
    interface_names.linear_acceleration.z: imu_sensor/linear_acceleration.z
  
    frame_id: imu_link

diff_cont:
  ros__parameters:

    publish_rate: 30.0

    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    # 0.335, 0.3375
    wheel_separation: 0.33
    wheel_radius: 0.035

    use_stamped_vel: false

    # open_loop: false    

    # wheels_per_side: x
    # wheel_separation_multiplier: x
    # left_wheel_radius_multiplier: x
    # right_wheel_radius_multiplier: x

    # odom_frame_id: x
    # pose_covariance_diagonal: x
    # twist_covariance_diagonal: x
    # open_loop: x
    # enable_odom_tf: x

    # cmd_vel_timeout: x
    # publish_limited_velocity: x
    # velocity_rolling_window_size: x
    

    # linear.x.has_velocity_limits: false
    # linear.x.has_acceleration_limits: false
    # linear.x.has_jerk_limits: false
    # linear.x.max_velocity: NAN
    # linear.x.min_velocity: NAN
    # linear.x.max_acceleration: NAN
    # linear.x.min_acceleration: NAN
    # linear.x.max_jerk: NAN
    # linear.x.min_jerk: NAN

    # angular.z.has_velocity_limits: false
    # angular.z.has_acceleration_limits: false
    # angular.z.has_jerk_limits: false
    # angular.z.max_velocity: NAN
    # angular.z.min_velocity: NAN
    # angular.z.max_acceleration: NAN
    # angular.z.min_acceleration: NAN
    # angular.z.max_jerk: NAN
    # angular.z.min_jerk: NAN
    
# joint_broad:
#   ros__parameters:

